project:
  type: website

website:
  title: "Embedded Medical Devices"
  description: "Duke BME 554L - Fall 2025"
  site-url: "https://mlp6.github.io/Embedded-Medical-Devices/"
  
  repo-url: "https://github.com/mlp6/Embedded-Medical-Devices/"
  repo-actions: [issue]

  sidebar:
    background: "#2d63ba"
    pinned: true
    align: center
    style: docked
    search: false
    collapse-level: 2
    contents:
      - section: "Course Information"
        contents:
        - href: course-syllabus.qmd
          text: Course Syllabus
        - href: bme-lab-policies.qmd
          text: "BME Lab Policies"
        - href: https://edstem.org/us/courses/90813/discussion
          text: Ed Discussion
        - href: https://canvas.duke.edu/courses/74002
          text: Canvas
        - href: https://www.gradescope.com/courses/1075664
          text: Gradescope
        - href: https://duke.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=7ce45649-7fe7-4549-9c8d-b33d00c57b38
          text: Panopto
        - href: software-install-tutorials.qmd
          text: "Software Installation & Tutorials"
        - href: faq.qmd
          text: FAQ
      - section: "Learning Modules"
        contents:
        - href: slides/zephyr-nrf52833dk-intro.qmd
          text: "Introduction to Zephyr & Nordic SoCs"
        - href: slides/event-driven-state-machine.qmd
          text: "Event-Driven State Machines"
        - href: slides/git-fundamentals.qmd
          text: "Git Fundamentals"
        - href: slides/c-programming.qmd
          text: "C Programming"
        - href: slides/zephyr-gpio-isr-callbacks.qmd
          text: "GPIO, ISR, and Callbacks"
        - href: slides/zephyr-timers.qmd
          text: "Timers"
        - href: slides/zephyr-threads-events.qmd
          text: "Threads and Kernel Events"
        - href: slides/zephyr-smf.qmd
          text: "State Machine Framework (SMF)"
        - href: slides/zephyr-adc.qmd
          text: "Analog-to-Digital Conversion (ADC)"
        - href: slides/zephyr-pwm.qmd
          text: "Pulse Width Modulation (PWM)"
        - href: slides/zephyr-serial-communication.qmd
          text: "Serial Communication (UART, I2C, SPI)"
        - href: slides/zephyr-ble.qmd
          text: "Bluetooth Low Energy (BLE)"
        - href: slides/zephyr-vbus.qmd
          text: "VBUS"
      - section: Labs
        contents:
        - href: labs/event-driven-state-machine-lab.qmd
          text: "Event-Driven State Machine Lab"
        - href: labs/git-fundamentals-lab.qmd
          text: "Git Fundamentals Lab"
        - href: labs/c-programming-lab.qmd
          text: "C Programming Lab"
        - href: labs/zephyr-gpio-isr-callbacks-lab.qmd
          text: "GPIO, ISR, and Callbacks Lab"
        - href: labs/zephyr-timers-lab.qmd
          text: "Timers Lab"
        - href: labs/zephyr-smf-lab.qmd
          text: "State Machine Framework (SMF) Refactor Lab"
        - href: labs/zephyr-threads-events-lab.qmd
          text: "Threads and Kernel Events Lab"
        - href: labs/zephyr-adc-lab.qmd
          text: "Analog-to-Digital Conversion (ADC) Lab"
        - href: labs/zephyr-pwm-lab.qmd
          text: "Pulse Width Modulation (PWM) Lab"
        - href: labs/ecg-temp-ble-lab.qmd
          text: "ECG, Temperature Sensor, and BLE Lab"
      - section: Resources
        contents:
        - href: resources/git.qmd
          text: "Git Version Control"
        - href: resources/technical_report.qmd
          text: "Technical Report Guidelines"
        - href: resources/state_diagram.qmd
          text: "State Diagram Preparation Tools"
        - href: resources/how-to-generate-ecg-waveforms.qmd
          text: "How to Generate ECG Waveforms"
        - href: resources/debugging.qmd
          text: "Zephyr: Debugging in VS Code"
        - href: resources/teaching_assistant_expectations.qmd
          text: "Teaching Assistant Expectations"
        - href: https://docs.nordicsemi.com/bundle/ps_nrf52833
          text: "nRF52833 Product Specifications"
        - href: https://docs.nordicsemi.com/
          text: Nordic Semiconductor Documentation

    page-footer:
      right: 'This page is built with [Quarto](https://quarto.org/).'
      left: "&copy; Copyright 2025, Mark Palmeri"

format:
  html:
    mainfont: Atkinson Hyperlegible
    highlight-style: a11y-light
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

linkcolor: "#5D737E"
toc: true
code-copy: hover
code-link: true
code-overflow: wrap